# Generated by Django 2.1.5 on 2019-01-14 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
